# -*- coding: utf-8 -*-
"""Lab 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1deTvu7FzmXOfO8oNEcs0rJePYWmauoGk
"""

from pathlib import Path
import re

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import TfidfVectorizer


# ---------------------------------------------------------------------
# 1. SETTINGS
# ---------------------------------------------------------------------

SEED = 8213026
DATA_DIR = Path(".").resolve()

TRAIN_FILE = DATA_DIR / "egs_text_training.csv"
INVESTIGATION_FILE = DATA_DIR / "egs_text_investigation.csv"

OUTPUT_DIR = DATA_DIR / "B1_outputs"
OUTPUT_DIR.mkdir(exist_ok=True)


# ---------------------------------------------------------------------
# 2. LOAD THE TWO DATASETS
# ---------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART B1 – TEXT PREPARATION AND EXPLORATORY ANALYSIS")
print("=" * 70)

train = pd.read_csv(TRAIN_FILE)
investigation = pd.read_csv(INVESTIGATION_FILE)

print("\n[1] DATASET LOADING")
print("-" * 70)
print(f"Training dataset:       {len(train):,} reports")
print(f"Investigation dataset:  {len(investigation):,} reports")

print("\nTraining columns:")
print(list(train.columns))

print("\nInvestigation columns:")
print(list(investigation.columns))


# ---------------------------------------------------------------------
# 3. BASIC DATA-QUALITY CHECKS
# ---------------------------------------------------------------------

print("\n[2] DATA-QUALITY CHECKS")
print("-" * 70)


def quality_summary(df, name):
    missing_total = int(df.isna().sum().sum())
    duplicate_rows = int(df.duplicated().sum())

    if "report_id" in df.columns:
        duplicate_ids = int(df["report_id"].duplicated().sum())
    else:
        duplicate_ids = 0

    print(f"\n{name}")
    print(f"Rows:                  {len(df):,}")
    print(f"Columns:               {len(df.columns):,}")
    print(f"Missing values:        {missing_total:,}")
    print(f"Duplicate rows:        {duplicate_rows:,}")
    print(f"Duplicate report IDs:  {duplicate_ids:,}")

    return {
        "dataset": name,
        "rows": len(df),
        "missing_values": missing_total,
        "duplicate_rows": duplicate_rows,
        "duplicate_report_ids": duplicate_ids,
    }


quality_rows = [
    quality_summary(train, "Training"),
    quality_summary(investigation, "Investigation"),
]

quality_df = pd.DataFrame(quality_rows)
quality_df.to_csv(OUTPUT_DIR / "B1_data_quality_summary.csv", index=False)


# ---------------------------------------------------------------------
# 4. CHECK REQUIRED FIELDS
# ---------------------------------------------------------------------

print("\n[3] REQUIRED FIELD CHECK")
print("-" * 70)

required_train = ["report_id", "title", "report_text", "source",
                   "published_at", "relevant_label"]

required_investigation = ["report_id", "title", "report_text", "source",
                          "published_at"]

missing_train_columns = [
    col for col in required_train if col not in train.columns
]

missing_investigation_columns = [
    col for col in required_investigation if col not in investigation.columns
]

if missing_train_columns:
    raise ValueError(
        f"Training file is missing required columns: {missing_train_columns}"
    )

if missing_investigation_columns:
    raise ValueError(
        "Investigation file is missing required columns: "
        f"{missing_investigation_columns}"
    )

print("All required B1 fields are present.")


# ---------------------------------------------------------------------
# 5. NORMALISE PUBLICATION DATES
# ---------------------------------------------------------------------

print("\n[4] PUBLICATION-DATE PREPARATION")
print("-" * 70)

train["published_at"] = pd.to_datetime(
    train["published_at"], errors="coerce"
)

investigation["published_at"] = pd.to_datetime(
    investigation["published_at"], errors="coerce"
)

print(
    f"Training date range:      "
    f"{train['published_at'].min().date()} to "
    f"{train['published_at'].max().date()}"
)

print(
    f"Investigation date range: "
    f"{investigation['published_at'].min().date()} to "
    f"{investigation['published_at'].max().date()}"
)


# ---------------------------------------------------------------------
# 6. CLASS BALANCE
# ---------------------------------------------------------------------

print("\n[5] HISTORICAL RELEVANCE CLASS BALANCE")
print("-" * 70)

class_counts = (
    train["relevant_label"]
    .value_counts()
    .sort_index()
)

class_balance = pd.DataFrame({
    "relevance_label": class_counts.index,
    "count": class_counts.values,
})

class_balance["percentage"] = (
    class_balance["count"] / len(train) * 100
)

label_names = {
    0: "Not relevant",
    1: "Relevant",
}

class_balance["label_description"] = (
    class_balance["relevance_label"]
    .map(label_names)
    .fillna("Other")
)

print(class_balance[
    ["relevance_label", "label_description", "count", "percentage"]
].to_string(index=False))

class_balance.to_csv(
    OUTPUT_DIR / "B1_class_balance.csv",
    index=False
)


# ---------------------------------------------------------------------
# 7. SOURCE DISTRIBUTION
# ---------------------------------------------------------------------

print("\n[6] SOURCE DISTRIBUTION")
print("-" * 70)

train_source = train["source"].value_counts().rename("training")
inv_source = investigation["source"].value_counts().rename("investigation")

source_distribution = pd.concat(
    [train_source, inv_source],
    axis=1
).fillna(0)

source_distribution["training"] = (
    source_distribution["training"].astype(int)
)

source_distribution["investigation"] = (
    source_distribution["investigation"].astype(int)
)

source_distribution["training_percentage"] = (
    source_distribution["training"] / len(train) * 100
)

source_distribution["investigation_percentage"] = (
    source_distribution["investigation"] / len(investigation) * 100
)

source_distribution = (
    source_distribution
    .reset_index()
    .rename(columns={"source": "report_source"})
)

print(source_distribution.to_string(index=False))

source_distribution.to_csv(
    OUTPUT_DIR / "B1_source_distribution.csv",
    index=False
)


# ---------------------------------------------------------------------
# 8. PUBLICATION-YEAR DISTRIBUTION
# ---------------------------------------------------------------------

print("\n[7] PUBLICATION-YEAR DISTRIBUTION")
print("-" * 70)

train_year = train["published_at"].dt.year.value_counts().rename("training")
inv_year = investigation["published_at"].dt.year.value_counts().rename(
    "investigation"
)

year_distribution = pd.concat(
    [train_year, inv_year],
    axis=1
).fillna(0).astype(int)

year_distribution = (
    year_distribution
    .sort_index()
    .reset_index()
    .rename(columns={"index": "publication_year"})
)

print(year_distribution.to_string(index=False))

year_distribution.to_csv(
    OUTPUT_DIR / "B1_publication_year_distribution.csv",
    index=False
)


# ---------------------------------------------------------------------
# 9. TEXT PREPARATION
# ---------------------------------------------------------------------

print("\n[8] TEXT PREPARATION")
print("-" * 70)


def clean_text(text):
    """
    Basic reproducible text normalisation.

    Operations:
      - convert missing values to empty strings
      - convert to lower case
      - replace URLs with the token 'url'
      - remove punctuation while retaining useful word characters
      - collapse repeated whitespace
    """
    if pd.isna(text):
        return ""

    text = str(text).lower()

    text = re.sub(
        r"https?://\S+|www\.\S+",
        " url ",
        text
    )

    text = re.sub(
        r"[^a-z0-9_\-\s]",
        " ",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    ).strip()

    return text


# Combine title and report_text.
train["combined_text"] = (
    train["title"].fillna("").astype(str)
    + " "
    + train["report_text"].fillna("").astype(str)
)

investigation["combined_text"] = (
    investigation["title"].fillna("").astype(str)
    + " "
    + investigation["report_text"].fillna("").astype(str)
)

train["clean_text"] = train["combined_text"].apply(clean_text)
investigation["clean_text"] = investigation["combined_text"].apply(clean_text)

print("Text fields combined: title + report_text")
print("Normalisation: lower case, URL replacement, punctuation handling")
print("Stop-word handling: English stop words removed by TF-IDF")
print("N-grams: unigrams and bigrams")


# ---------------------------------------------------------------------
# 10. TF-IDF EXPLORATION
# ---------------------------------------------------------------------

print("\n[9] TF-IDF EXPLORATION")
print("-" * 70)

# Use only historically relevant reports for this exploratory view.
relevant_mask = train["relevant_label"] == 1

relevant_text = train.loc[
    relevant_mask,
    "clean_text"
]

vectorizer = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1, 2),
    min_df=2,
    token_pattern=r"(?u)\b[a-zA-Z][a-zA-Z0-9_-]*\b"
)

tfidf_matrix = vectorizer.fit_transform(relevant_text)

mean_scores = np.asarray(
    tfidf_matrix.mean(axis=0)
).ravel()

terms = np.array(
    vectorizer.get_feature_names_out()
)

top_n = 15

top_indices = mean_scores.argsort()[::-1][:top_n]

top_tfidf = pd.DataFrame({
    "term_or_phrase": terms[top_indices],
    "mean_tfidf": mean_scores[top_indices],
})

print("\nTop TF-IDF terms/phrases in relevant reports:")
print(top_tfidf.to_string(index=False))

top_tfidf.to_csv(
    OUTPUT_DIR / "B1_top_tfidf_terms.csv",
    index=False
)


# ---------------------------------------------------------------------
# 11. FIGURE B1-1 – CLASS BALANCE
# ---------------------------------------------------------------------

print("\n[10] CREATING FIGURE B1-1")
print("-" * 70)

class_plot = class_balance.copy()

class_plot["display_label"] = (
    class_plot["relevance_label"]
    .map(label_names)
    .fillna("Other")
)

plt.figure(figsize=(8, 5))

bars = plt.bar(
    class_plot["display_label"],
    class_plot["count"]
)

plt.title(
    "Figure B1-1: Historical Training Class Balance"
)

plt.xlabel(
    "Historical relevance class"
)

plt.ylabel(
    "Number of reports"
)

for bar, value in zip(
    bars,
    class_plot["count"]
):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        value,
        f"{int(value):,}",
        ha="center",
        va="bottom"
    )

plt.tight_layout()

class_chart = OUTPUT_DIR / "B1_1_class_balance.png"

plt.savefig(
    class_chart,
    dpi=200,
    bbox_inches="tight"
)

plt.close()

print(f"Saved: {class_chart}")


# ---------------------------------------------------------------------
# 12. FIGURE B1-2 – SOURCE DISTRIBUTION
# ---------------------------------------------------------------------

print("\n[11] CREATING FIGURE B1-2")
print("-" * 70)

plot_df = source_distribution.copy()

# Sort by total volume so the visualisation is easy to interpret.
plot_df["total"] = (
    plot_df["training"]
    + plot_df["investigation"]
)

plot_df = plot_df.sort_values(
    "total",
    ascending=True
)

y = np.arange(len(plot_df))
height = 0.36

plt.figure(figsize=(9, 6))

plt.barh(
    y - height / 2,
    plot_df["training"],
    height,
    label="Training"
)

plt.barh(
    y + height / 2,
    plot_df["investigation"],
    height,
    label="Investigation"
)

plt.yticks(
    y,
    plot_df["report_source"]
)

plt.xlabel(
    "Number of reports"
)

plt.ylabel(
    "Report source"
)

plt.title(
    "Figure B1-2: Report Distribution by Source"
)

plt.legend()

plt.tight_layout()

source_chart = OUTPUT_DIR / "B1_2_source_distribution.png"

plt.savefig(
    source_chart,
    dpi=200,
    bbox_inches="tight"
)

plt.close()

print(f"Saved: {source_chart}")


# ---------------------------------------------------------------------
# 13. SAVE PREPARED DATA
# ---------------------------------------------------------------------

print("\n[12] SAVING PREPARED DATA")
print("-" * 70)

train_output_columns = [
    col for col in [
        "report_id",
        "title",
        "source",
        "published_at",
        "relevant_label",
        "clean_text",
    ]
    if col in train.columns
]

investigation_output_columns = [
    col for col in [
        "report_id",
        "title",
        "source",
        "published_at",
        "clean_text",
    ]
    if col in investigation.columns
]

train[
    train_output_columns
].to_csv(
    OUTPUT_DIR / "B1_training_prepared.csv",
    index=False
)

investigation[
    investigation_output_columns
].to_csv(
    OUTPUT_DIR / "B1_investigation_prepared.csv",
    index=False
)


# ---------------------------------------------------------------------
# 14. FINAL B1 SUMMARY
# ---------------------------------------------------------------------

print("\n" + "=" * 70)
print("PART B1 COMPLETE")
print("=" * 70)

print(f"""
Training reports:          {len(train):,}
Investigation reports:     {len(investigation):,}

Training missing values:   {int(train.isna().sum().sum()):,}
Investigation missing:     {int(investigation.isna().sum().sum()):,}

Training duplicates:       {int(train.duplicated().sum()):,}
Investigation duplicates:  {int(investigation.duplicated().sum()):,}

Relevant reports:          {int((train["relevant_label"] == 1).sum()):,}
Not relevant reports:      {int((train["relevant_label"] == 0).sum()):,}

Output folder:
    {OUTPUT_DIR}

Main B1 outputs:
    B1_data_quality_summary.csv
    B1_class_balance.csv
    B1_source_distribution.csv
    B1_publication_year_distribution.csv
    B1_top_tfidf_terms.csv
    B1_training_prepared.csv
    B1_investigation_prepared.csv
    B1_1_class_balance.png
    B1_2_source_distribution.png
""")

print("B1 processing finished successfully.")

"""
SAS821S Lab 3 - Part B2
IOC / Entity Extraction and Operational Relevance

Inputs:
  egs_text_investigation.csv
  egs_ioc_feed.csv

Output:
  extracted_iocs.csv

The script demonstrates how the B2 results were produced:
1. Load investigation reports and IOC feed.
2. Extract IPv4 addresses, domains, SHA-256 hashes, threat actors and malware/tools.
3. Match extracted indicators to the IOC feed.
4. Assign confidence and analytical relevance.
5. Preserve report IDs and IOC IDs for traceability.
"""

import re
from pathlib import Path
import pandas as pd

SEED = 8213026
BASE = Path(".").resolve()

REPORT_FILE = BASE / "egs_text_investigation.csv"
IOC_FILE = BASE / "egs_ioc_feed.csv"
OUTPUT_FILE = BASE / "extracted_iocs.csv"


# -----------------------------
# 1. Load supplied evidence
# -----------------------------
reports = pd.read_csv(REPORT_FILE)
ioc_feed = pd.read_csv(IOC_FILE)

required_report_cols = {"report_id", "title", "report_text"}
missing = required_report_cols - set(reports.columns)
if missing:
    raise ValueError(f"Investigation file is missing columns: {sorted(missing)}")

# Combine title and report text so entities can occur in either field.
reports["combined_text"] = (
    reports["title"].fillna("").astype(str) + " " +
    reports["report_text"].fillna("").astype(str)
)


# -----------------------------
# 2. Transparent extraction rules
# -----------------------------
IP_RE = re.compile(
    r"\b(?:(?:25[0-5]|2[0-4]\d|1?\d?\d)\.){3}"
    r"(?:25[0-5]|2[0-4]\d|1?\d?\d)\b"
)

SHA256_RE = re.compile(r"\b[a-fA-F0-9]{64}\b")

DOMAIN_RE = re.compile(
    r"\b(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+"
    r"[a-zA-Z]{2,63}\b"
)

# These are named entities appearing in the supplied Lab 3 scenario.
THREAT_ACTORS = [
    "Kalahari Jackal",
]

MALWARE_TOOLS = [
    "Sandstorm Loader",
    "PowerShell",
]


def extract_regex_entities(text):
    """Extract technical indicators with transparent regular expressions."""
    entities = []

    for value in sorted(set(IP_RE.findall(text))):
        entities.append(("IPv4", value))

    for value in sorted(set(SHA256_RE.findall(text.lower()))):
        entities.append(("SHA-256", value.lower()))

    # Remove domains that are simply part of a URL/IP context.
    for value in sorted(set(DOMAIN_RE.findall(text))):
        entities.append(("Domain", value.lower()))

    return entities


def extract_named_entities(text):
    """Extract named actors and malware/tools from an explicit allow-list."""
    lower_text = text.lower()
    entities = []

    for name in THREAT_ACTORS:
        if name.lower() in lower_text:
            entities.append(("Threat Actor", name))

    for name in MALWARE_TOOLS:
        if name.lower() in lower_text:
            entities.append(("Malware/Tool", name))

    return entities


# -----------------------------
# 3. Build a normalised IOC feed
# -----------------------------
def find_column(columns, candidates):
    """Return the first IOC-feed column matching a candidate name."""
    lower_map = {str(c).strip().lower(): c for c in columns}

    for candidate in candidates:
        if candidate.lower() in lower_map:
            return lower_map[candidate.lower()]

    # Flexible fallback for common naming patterns.
    for c in columns:
        lc = str(c).strip().lower()
        if any(term in lc for term in candidates):
            return c

    return None


ioc_value_col = find_column(
    ioc_feed.columns,
    ["ioc_value", "indicator", "entity_value", "value", "ioc"]
)
ioc_id_col = find_column(
    ioc_feed.columns,
    ["ioc_id", "indicator_id", "id"]
)
confidence_col = find_column(
    ioc_feed.columns,
    ["confidence", "confidence_level"]
)
first_seen_col = find_column(
    ioc_feed.columns,
    ["first_seen", "published_at", "date_added", "created_at"]
)
last_seen_col = find_column(
    ioc_feed.columns,
    ["last_seen", "updated_at"]
)
context_col = find_column(
    ioc_feed.columns,
    ["context", "description", "threat_context", "notes"]
)

if ioc_value_col is None:
    raise ValueError(
        "Could not identify the IOC value column in egs_ioc_feed.csv. "
        "Expected a field such as ioc_value, indicator or entity_value."
    )

# Normalised lookup: indicator -> one or more feed rows.
ioc_lookup = {}
for _, row in ioc_feed.iterrows():
    raw = row.get(ioc_value_col)
    if pd.isna(raw):
        continue
    value = str(raw).strip().lower()
    if value:
        ioc_lookup.setdefault(value, []).append(row)


# -----------------------------
# 4. Confidence, recency and relevance
# -----------------------------
def confidence_from_feed(row):
    if confidence_col is None:
        return "Matched"

    value = str(row.get(confidence_col, "")).strip()
    return value if value else "Matched"


def relevance_for(entity_type, entity_value, matched):
    """
    Transparent analytical relevance rule.

    High:
      direct IOC-feed match or a named actor/malware strongly linked
      to the supplied vendor-to-OT scenario.

    Medium:
      plausible campaign artefact requiring validation.

    Context:
      useful named context that is not itself an IOC.

    Low:
      generic extracted entity with little case relevance.
    """
    value = entity_value.lower()

    if matched:
        return "High"

    if entity_type == "Threat Actor" and value == "kalahari jackal":
        return "Context"

    if entity_type == "Malware/Tool" and value == "sandstorm loader":
        return "Context"

    if entity_type == "Domain" and value.endswith(".example"):
        return "Medium"

    if entity_type == "IPv4":
        return "Medium"

    return "Low"


# -----------------------------
# 5. Extract and match
# -----------------------------
records = []

for _, report in reports.iterrows():
    report_id = report["report_id"]
    text = report["combined_text"]

    entities = extract_regex_entities(text)
    entities.extend(extract_named_entities(text))

    # Remove duplicates within a report.
    seen = set()

    for entity_type, entity_value in entities:
        key = (entity_type, str(entity_value).lower())
        if key in seen:
            continue
        seen.add(key)

        normalised = str(entity_value).strip().lower()
        matches = ioc_lookup.get(normalised, [])
        matched = bool(matches)

        if matches:
            # Keep one row per matching IOC-feed record.
            for ioc_row in matches:
                ioc_id = (
                    str(ioc_row[ioc_id_col])
                    if ioc_id_col is not None and not pd.isna(ioc_row[ioc_id_col])
                    else ""
                )

                records.append({
                    "report_id": report_id,
                    "entity_type": entity_type,
                    "entity_value": entity_value,
                    "analytical_relevance": relevance_for(
                        entity_type, entity_value, True
                    ),
                    "ioc_id": ioc_id,
                    "confidence": confidence_from_feed(ioc_row),
                    "first_seen": (
                        ioc_row[first_seen_col]
                        if first_seen_col is not None else ""
                    ),
                    "last_seen": (
                        ioc_row[last_seen_col]
                        if last_seen_col is not None else ""
                    ),
                    "context": (
                        ioc_row[context_col]
                        if context_col is not None else ""
                    ),
                })
        else:
            records.append({
                "report_id": report_id,
                "entity_type": entity_type,
                "entity_value": entity_value,
                "analytical_relevance": relevance_for(
                    entity_type, entity_value, False
                ),
                "ioc_id": "",
                "confidence": "Not matched",
                "first_seen": "",
                "last_seen": "",
                "context": "",
            })


# -----------------------------
# 6. Export required B2 output
# -----------------------------
output = pd.DataFrame(records)

required_output_cols = [
    "report_id",
    "entity_type",
    "entity_value",
    "analytical_relevance",
]

# The four rubric-required columns come first; traceability fields follow.
extra_cols = [
    "ioc_id",
    "confidence",
    "first_seen",
    "last_seen",
    "context",
]

output = output[
    [c for c in required_output_cols + extra_cols if c in output.columns]
]

output = output.drop_duplicates().sort_values(
    ["report_id", "entity_type", "entity_value"]
)

output.to_csv(OUTPUT_FILE, index=False)


# -----------------------------
# 7. Console evidence summary
# -----------------------------
print("=" * 70)
print("SAS821S LAB 3 - PART B2 IOC / ENTITY EXTRACTION")
print("=" * 70)
print(f"Investigation reports loaded : {len(reports):,}")
print(f"IOC feed records loaded      : {len(ioc_feed):,}")
print(f"Extracted entity rows        : {len(output):,}")
print(f"Unique report IDs            : {output['report_id'].nunique():,}")
print(f"Unique IOC IDs matched       : "
      f"{output.loc[output['ioc_id'].astype(str).str.len() > 0, 'ioc_id'].nunique():,}")

print("\nEntity types:")
print(output["entity_type"].value_counts().to_string())

print("\nMatched IOC evidence:")
matched = output[output["ioc_id"].astype(str).str.len() > 0]
if matched.empty:
    print("No direct IOC-feed matches found.")
else:
    cols = ["report_id", "entity_type", "entity_value", "ioc_id",
            "confidence", "analytical_relevance"]
    print(matched[cols].to_string(index=False))

print("\nRequired output:")
print(OUTPUT_FILE)
print("=" * 70)

# SAS821S Security Analytics - Lab 3 Part B3
# TF-IDF text classifier, investigation scoring and adversarial text analysis

import os, re
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from pathlib import Path # Import Path

SEED = 8213026
BASE = Path(".").resolve()

def clean_text(s):
    s = str(s).lower()
    s = re.sub(r"https?://\S+|www\.\S+", " url ", s)
    s = re.sub(r"[^a-zA-Z0-9_\-\s]", " ", s)
    return re.sub(r"\s+", " ", s).strip()

training = pd.read_csv(BASE / "egs_text_training.csv")
investigation = pd.read_csv(BASE / "egs_text_investigation.csv")
adversarial = pd.read_csv(BASE / "egs_adversarial_text_cases.csv")

train_text = (training["title"].fillna("") + " " + training["report_text"].fillna("")).map(clean_text)
inv_text = (investigation["title"].fillna("") + " " + investigation["report_text"].fillna("")).map(clean_text)

X_train_text, X_test_text, y_train, y_test = train_test_split(
    train_text, training["relevant_label"],
    test_size=0.20, stratify=training["relevant_label"], random_state=SEED
)

vectorizer = TfidfVectorizer(
    stop_words="english", ngram_range=(1, 2), min_df=2,
    token_pattern=r"(?u)\b[a-zA-Z][a-zA-Z0-9_-]*\b"
)

X_train = vectorizer.fit_transform(X_train_text)
X_test = vectorizer.transform(X_test_text)

model = LogisticRegression(max_iter=2000, random_state=SEED)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = cm.ravel()

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
fnr = fn / (fn + tp)

print("\nB3 MODEL EVALUATION")
print("Confusion matrix:")
print(cm)
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"False-negative rate: {fnr:.4f}")

# Investigation ranking
inv_matrix = vectorizer.transform(inv_text)
inv_probs = model.predict_proba(inv_matrix)[:, 1]
feature_names = vectorizer.get_feature_names_out()
coef = model.coef_[0]

ranked = investigation[["report_id", "published_at", "source", "title"]].copy()
ranked["predicted_relevance_probability"] = inv_probs

key_terms = []
for row_idx in ranked.index:
    scores = inv_matrix[row_idx].multiply(coef).toarray().ravel()
    best = scores.argsort()[::-1]
    terms = [feature_names[i] for i in best if scores[i] > 0][:5]
    key_terms.append(", ".join(terms))

ranked["key_terms"] = key_terms
ranked = ranked.sort_values("predicted_relevance_probability", ascending=False)
ranked.insert(0, "rank", range(1, len(ranked) + 1))
ranked.head(15).to_csv(BASE / "top_15_relevant_reports.csv", index=False)

# Adversarial comparison
rows = []
for _, r in adversarial.iterrows():
    p1 = model.predict_proba(vectorizer.transform([clean_text(r["original_text"])]))[0, 1]
    p2 = model.predict_proba(vectorizer.transform([clean_text(r["modified_text"])]))[0, 1]
    change = p2 - p1
    pct = (change / p1 * 100) if p1 else None
    rows.append({
        "case_id": r["case_id"],
        "evasion_technique": r["evasion_technique"],
        "original_probability": p1,
        "modified_probability": p2,
        "probability_change": change,
        "percentage_change": pct
    })

pd.DataFrame(rows).to_csv(
    BASE / "adversarial_text_probability_changes.csv", index=False
)

print("\nB3 investigation and adversarial outputs created.")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# Assuming input files are in the current working directory or a 'data' subfolder
# If your files are in a different location, please adjust this path.
INPUT_DIR = Path(".") # Changed from Path("/mnt/data/c_inputs_correct")
OUTPUT_DIR = Path("Lab3_Part_C2_Outputs") # Changed to create in current working directory
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SEED = 8213026
ITERATIONS = 1000
MAX_STEPS = 30
INITIAL_INFECTED = "VENDOR-LT-07"
VENDOR_PATH_ASSETS = {"VENDOR-LT-07", "VPN-GW-01", "VENDOR-DMZ-01"}

assets = pd.read_csv(INPUT_DIR / "egs_asset_inventory.csv")
posture = pd.read_csv(INPUT_DIR / "egs_host_security_posture.csv")
edges = pd.read_csv(INPUT_DIR / "egs_network_topology_edges.csv")
scenarios = pd.read_csv(INPUT_DIR / "egs_simulation_scenarios.csv")

asset_map = assets.set_index("asset_id").to_dict("index")
posture_map = posture.set_index("asset_id").to_dict("index")

def adjusted_edge_probability(edge, scenario):
    p = float(edge["base_transmission_probability"])
    target = edge["target_asset"]
    source_zone = edge["source_zone"]
    target_zone = edge["target_zone"]

    # Patch vendor laptop, VPN gateway and vendor broker.
    if scenario["patch_factor"] < 1 and target in VENDOR_PATH_ASSETS:
        p *= float(scenario["patch_factor"])

    # Reduce DMZ-to-OT/OT-DMZ and OT lateral movement.
    if scenario["segmentation_factor"] < 1:
        dmz_to_ot = (
            source_zone in {"DMZ", "OT-DMZ"}
            and target_zone in {"OT-DMZ", "OT"}
        )
        ot_lateral = source_zone == "OT" and target_zone == "OT"
        if dmz_to_ot or ot_lateral:
            p *= float(scenario["segmentation_factor"])

    return min(max(p, 0.0), 1.0)

def simulate_once(scenario, rng):
    infected = {INITIAL_INFECTED: 0}
    newly_infected = [INITIAL_INFECTED]
    step = 0
    time_to_ot = None
    safety_reached = False

    while newly_infected and step < MAX_STEPS:
        step += 1
        new_assets = []

        for source in list(infected):
            infection_step = infected[source]

            for _, edge in edges[edges["source_asset"] == source].iterrows():
                target = edge["target_asset"]

                if target in infected:
                    continue

                probability = adjusted_edge_probability(edge, scenario)

                # Rapid isolation applies to compromised Windows sources.
                source_os = str(posture_map[source]["operating_system"])
                delay = int(scenario["isolation_delay_steps"])

                if "Windows" in source_os and delay < 99:
                    elapsed = step - infection_step
                    if elapsed >= delay:
                        probability *= float(
                            scenario["post_detection_transmission_factor"]
                        )

                if rng.random() < probability:
                    infected[target] = step
                    new_assets.append(target)

                    if asset_map[target]["zone"] == "OT" and time_to_ot is None:
                        time_to_ot = step

                    if asset_map[target]["zone"] == "Safety":
                        safety_reached = True

        newly_infected = new_assets

    return {
        "ot_reached": any(asset_map[a]["zone"] == "OT" for a in infected),
        "safety_reached": safety_reached,
        "critical_assets_infected": sum(
            asset_map[a]["criticality"] == "Critical" for a in infected
        ),
        "total_assets_infected": len(infected),
        "time_to_ot": time_to_ot,
    }

run_rows = []

for _, scenario in scenarios.iterrows():
    scenario_number = int(str(scenario["scenario_id"])[1:])
    rng = np.random.default_rng(SEED + scenario_number)

    for iteration in range(1, ITERATIONS + 1):
        result = simulate_once(scenario.to_dict(), rng)
        result.update({
            "scenario_id": scenario["scenario_id"],
            "scenario_name": scenario["scenario_name"],
            "iteration": iteration
        })
        run_rows.append(result)

runs = pd.DataFrame(run_rows)

summary_rows = []
for scenario_id, group in runs.groupby("scenario_id", sort=True):
    summary_rows.append({
        "scenario_id": scenario_id,
        "scenario_name": group["scenario_name"].iloc[0],
        "iterations": len(group),
        "probability_reaching_ot": group["ot_reached"].mean(),
        "probability_reaching_safety_zone": group["safety_reached"].mean(),
        "mean_critical_assets_infected": group["critical_assets_infected"].mean(),
        "mean_total_assets_infected": group["total_assets_infected"].mean(),
        "median_time_to_ot_steps": group.loc[
            group["time_to_ot"].notna(), "time_to_ot"
        ].median(),
        "p95_total_assets_infected": group["total_assets_infected"].quantile(0.95)
    })

summary = pd.DataFrame(summary_rows)

baseline = summary.loc[summary["scenario_id"] == "S0"].iloc[0]

summary["ot_absolute_risk_reduction"] = (
    baseline["probability_reaching_ot"] - summary["probability_reaching_ot"]
)
summary["ot_relative_risk_reduction_pct"] = (
    summary["ot_absolute_risk_reduction"]
    / baseline["probability_reaching_ot"] * 100
)

summary["safety_absolute_risk_reduction"] = (
    baseline["probability_reaching_safety_zone"]
    - summary["probability_reaching_safety_zone"]
)
summary["safety_relative_risk_reduction_pct"] = (
    summary["safety_absolute_risk_reduction"]
    / baseline["probability_reaching_safety_zone"] * 100
)

summary.to_csv(OUTPUT_DIR / "simulation_summary.csv", index=False)
runs.to_csv(OUTPUT_DIR / "simulation_run_results.csv", index=False)

x = np.arange(len(summary))
width = 0.36
labels = summary["scenario_name"]

plt.figure(figsize=(10, 6))
plt.bar(x - width/2, summary["probability_reaching_ot"], width, label="Reach OT")
plt.bar(x + width/2, summary["probability_reaching_safety_zone"], width,
        label="Reach Safety Zone")
plt.xticks(x, labels, rotation=20, ha="right")
plt.ylabel("Probability")
plt.title("C2.1 Probability of Reaching OT and Safety Zone")
plt.legend()
plt.tight_layout()
plt.savefig(OUTPUT_DIR / "C2_1_reach_probability_comparison.png", dpi=200)
plt.close()

plt.figure(figsize=(10, 6))
plt.bar(x - width/2, summary["mean_total_assets_infected"], width,
        label="Mean total assets infected")
plt.bar(x + width/2, summary["mean_critical_assets_infected"], width,
        label="Mean critical assets infected")
plt.xticks(x, labels, rotation=20, ha="right")
plt.ylabel("Mean infected assets")
plt.title("C2.2 Mean Propagation Impact by Control Scenario")
plt.legend()
plt.tight_layout()
plt.savefig(OUTPUT_DIR / "C2_2_mean_infected_assets.png", dpi=200)
plt.close()

print(summary.round(3).to_string(index=False))

"""
SAS821S Lab 3 - D1 Predictive Risk Model
Predict incident_within_7d using egs_daily_risk_training.csv.

Fixed seed: 8213026
Split: 70% train / 15% validation / 15% test, stratified.
Model: Standardised Logistic Regression.
Operating threshold: selected on validation data to achieve recall >= 0.75
while maximising precision; final metrics are reported on the held-out test set.
"""
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix, accuracy_score, precision_score,
    recall_score, f1_score, roc_auc_score
)

SEED = 8213026
DATA = Path(".").resolve()
INPUT = DATA / "egs_daily_risk_training.csv"

df = pd.read_csv(INPUT)
X = df.drop(columns=["incident_within_7d", "date"])
y = df["incident_within_7d"]

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, stratify=y, random_state=SEED
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=SEED
)

model = Pipeline([
    ("scale", StandardScaler()),
    ("classifier", LogisticRegression(max_iter=2000, random_state=SEED))
])
model.fit(X_train, y_train)

val_prob = model.predict_proba(X_val)[:, 1]
thresholds = np.round(np.arange(0.10, 0.71, 0.01), 2)
choices = []
for t in thresholds:
    p = (val_prob >= t).astype(int)
    choices.append({
        "threshold": t,
        "precision": precision_score(y_val, p, zero_division=0),
        "recall": recall_score(y_val, p, zero_division=0),
        "f1": f1_score(y_val, p, zero_division=0),
        "alerts": int(p.sum())
    })
threshold_df = pd.DataFrame(choices)
eligible = threshold_df[threshold_df["recall"] >= 0.75]
threshold = float(
    eligible.sort_values(["precision", "f1", "threshold"],
                         ascending=[False, False, False]).iloc[0]["threshold"]
)

test_prob = model.predict_proba(X_test)[:, 1]
test_pred = (test_prob >= threshold).astype(int)
cm = confusion_matrix(y_test, test_pred)
tn, fp, fn, tp = cm.ravel()

metrics = {
    "Model": "Standardised Logistic Regression",
    "Seed": SEED,
    "Train": len(X_train),
    "Validation": len(X_val),
    "Test": len(X_test),
    "Threshold": threshold,
    "Accuracy": accuracy_score(y_test, test_pred),
    "Precision": precision_score(y_test, test_pred, zero_division=0),
    "Recall": recall_score(y_test, test_pred, zero_division=0),
    "F1": f1_score(y_test, test_pred, zero_division=0),
    "FNR": fn / (fn + tp),
    "ROC_AUC": roc_auc_score(y_test, test_prob),
    "TN": tn, "FP": fp, "FN": fn, "TP": tp
}

print("D1 model results")
for k, v in metrics.items():
    print(f"{k}: {v}")
print("\nConfusion matrix:")
print(cm)

from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

SEED = 8213026
BASE = Path(".").resolve()
TRAIN = BASE/'egs_daily_risk_training.csv'
INV = BASE/'egs_daily_risk_investigation.csv'
LOGS = BASE/'egs_security_event_logs.csv'
OUT = BASE/'Lab3_D2_Outputs'
OUT.mkdir(exist_ok=True)

train = pd.read_csv(TRAIN)
inv = pd.read_csv(INV)
logs = pd.read_csv(LOGS)

features = [c for c in train.columns if c not in ['incident_within_7d','date']]
X = train[features]
y = train['incident_within_7d']
X_train, X_tmp, y_train, y_tmp = train_test_split(X, y, test_size=.30, stratify=y, random_state=SEED)
X_val, X_test, y_val, y_test = train_test_split(X_tmp, y_tmp, test_size=.50, stratify=y_tmp, random_state=SEED)

model = Pipeline([
    ('scale', StandardScaler()),
    ('classifier', LogisticRegression(max_iter=2000, random_state=SEED))
])
model.fit(X_train, y_train)

inv['risk_probability'] = model.predict_proba(inv[features])[:,1]
inv['risk_probability_pct'] = inv['risk_probability']*100
inv['risk_flag_0_31'] = inv['risk_probability'] >= 0.31
inv['risk_rank'] = inv['risk_probability'].rank(method='first', ascending=False).astype(int)

# Required top-10 output
cols = ['risk_rank','date','risk_probability','risk_probability_pct','risk_flag_0_31'] + features
inv.sort_values(['risk_probability','date'], ascending=[False, True]).head(10)[cols].to_csv(OUT/'top_10_risk_days.csv', index=False)

# Full scored investigation for reproducibility
inv.sort_values('date').to_csv(OUT/'investigation_risk_scores.csv', index=False)

# Risk probability over time
plot_df = inv.sort_values('date').copy()
plot_df['date'] = pd.to_datetime(plot_df['date'])
fig, ax = plt.subplots(figsize=(10.5,5.2))
ax.plot(plot_df['date'], plot_df['risk_probability'], marker='o', linewidth=1.8, markersize=4)
ax.axhline(0.31, linestyle='--', linewidth=1.2, label='D1 operating threshold = 0.31')
ax.set_title('D2 Risk Probability Over Time — Investigation Period')
ax.set_xlabel('Date')
ax.set_ylabel('Predicted probability of incident within 7 days')
ax.set_ylim(0, 1.05)
ax.grid(True, alpha=0.25)
ax.legend()
fig.autofmt_xdate()
fig.tight_layout()
fig.savefig(OUT/'D2_1_risk_probability_over_time.png', dpi=200)
plt.close(fig)

# Escalation summary
first = plot_df[plot_df.risk_probability >= .31].iloc[0]
prev = plot_df[plot_df.date < first.date].iloc[-1]
esc = pd.DataFrame([
    {
    'operating_threshold': .31,
    'earliest_defensible_escalation_date': first.date.strftime('%Y-%m-%d'),
    'risk_probability': first.risk_probability,
    'previous_date': prev.date.strftime('%Y-%m-%d'),
    'previous_risk_probability': prev.risk_probability,
    'risk_jump_absolute': first.risk_probability-prev.risk_probability,
    'interpretation': 'Escalate to active investigation because risk probability crosses the D1 threshold and remains elevated through the rest of the investigation period.'
}
])
esc.to_csv(OUT/'D2_escalation_point.csv', index=False)


selected_event_ids = ['EVT01574','EVT01575','EVT01576','EVT01577','EVT01578','EVT01579','EVT01580','EVT01581','EVT01582','EVT01583','EVT01584','EVT01585','EVT01586','EVT01588','EVT01589','EVT01590']
e = logs[logs.event_id.isin(selected_event_ids)].copy()
e['timestamp'] = pd.to_datetime(e['timestamp'])

def interpretation(r):
    m = {
      'EVT01574':'Initial vendor-path authentication failure from IOC9001 source; suspicious access attempt.',
      'EVT01575':'Repeated authentication failure from the same external source; strengthens attempted-intrusion assessment.',
      'EVT01576':'Successful vendor login from a new device after MFA approval; successful access to the vendor path.',
      'EVT01577':'Unsigned Sandstorm Loader binary launched PowerShell on VENDOR-LT-07; endpoint execution evidence.',
      'EVT01578':'Periodic DNS beacon to desert-sync.example; consistent with IOC9002 C2 indicator.',
      'EVT01579':'RDP session from vendor endpoint/path using IOC9001 source; lateral movement evidence.',
      'EVT01580':'Vendor account authenticated to OT-JUMP-01 outside approved window; successful OT jump-host access.',
      'EVT01581':'Credential-dumping attempt was blocked by EDR; attack action attempted, not successful credential theft.',
      'EVT01582':'Unexpected RDP access to ENG-WS-01; successful engineering-workstation access.',
      'EVT01583':'Sequential scan of PLC subnet; OT reconnaissance.',
      'EVT01584':'Bulk historian tag enumeration; OT information discovery.',
      'EVT01585':'Modbus function 43 device-identification query blocked; PLC query attempted but blocked.',
      'EVT01586':'Modbus register-write attempt blocked by OT firewall; control manipulation was attempted, not confirmed successful.',
      'EVT01588':'Outbound connection to IOC9003 blocked by OT egress policy; C2/exfiltration path prevented at this point.',
      'EVT01589':'SOC isolated OT-JUMP-01; containment action.',
      'EVT01590':'Vendor VPN session terminated; containment completed for the observed session.'}
    return m.get(r.event_id,'')

e['observed_action'] = e['event_type'] + ' — ' + e['details'].fillna('')
e['analytical_interpretation'] = e.apply(interpretation, axis=1)
e['evidence_source'] = e['source_type']

timeline_rows=[]
for _,r in e.sort_values('timestamp').iterrows():
    timeline_rows.append({'timestamp':r.timestamp,'evidence_id':r.event_id,'evidence_type':'Event','evidence_source':r.evidence_source,'observed_action':r.observed_action,'analytical_interpretation':r.analytical_interpretation})

intel = [
 ('RPT9001','Report','2026-10-14','Kalahari Jackal abuses vendor remote access','Sets campaign context: compromised maintenance vendors, password spraying/MFA prompts, RDP to OT jump servers and PowerShell.'),
 ('IOC9005','IOC','2026-10-14','maintenance-check.example','Medium-confidence credential-harvesting domain; supports phishing context but is not proof alone.'),
 ('RPT9002','Report','2026-10-15','Sandstorm Loader C2 infrastructure','Links periodic DNS to desert-sync.example and outbound TLS to 198.51.100.44.'),
 ('IOC9001','IOC','2026-10-16','203.0.113.77','High-confidence vendor access infrastructure; matches EVT01574–EVT01576.'),
 ('IOC9002','IOC','2026-10-16','desert-sync.example','High-confidence Sandstorm Loader C2 domain; matches EVT01578 and EVT01587.'),
 ('IOC9003','IOC','2026-10-16','198.51.100.44','High-confidence C2 IP; outbound connection was blocked in EVT01588.'),
 ('IOC9004','IOC','2026-10-16','Sandstorm Loader SHA-256','High-confidence malware hash; endpoint evidence in EVT01577 identifies sandstorm-loader.bin.'),
 ('RPT9003','Report','2026-10-16','Industrial protocol reconnaissance linked to current campaign','Describes movement to engineering workstations, Modbus reconnaissance and attempted register writes; notes no destructive effect where filtering is active.'),
 ('RPT9004','Report','2026-10-16','Sandstorm Loader technical profile','Associates the supplied hash with PowerShell, credential access and DNS beaconing.'),
 ('RPT9005','Report','2026-10-17','Energy vendor phishing lure observed','Describes credential-harvesting lure and use of compromised accounts outside maintenance windows.'),
]
for eid,etype,ts,title,interp in intel:
    timeline_rows.append({'timestamp':pd.to_datetime(ts), 'evidence_id':eid,'evidence_type':etype,'evidence_source':'Threat intelligence / investigation report','observed_action':title,'analytical_interpretation':interp})

timeline = pd.DataFrame(timeline_rows).sort_values(['timestamp','evidence_type','evidence_id'])
timeline.to_csv(OUT/'D2_correlated_timeline.csv', index=False)

# Evidence conclusion matrix
conclusion = pd.DataFrame([
 ['Attempted intrusion','Confirmed / high confidence','Failed logins followed by successful login from IOC9001 source, malicious endpoint execution, C2 DNS, lateral movement and OT reconnaissance.','EVT01574–EVT01584; IOC9001–IOC9004; RPT9001–RPT9005'],
 ['Successful OT access','Confirmed, limited scope','Vendor account successfully authenticated to OT-JUMP-01 and accessed ENG-WS-01.','EVT01580, EVT01582'],
 ['Successful control-system manipulation','Not confirmed','A Modbus register-write was attempted but explicitly blocked by the OT firewall.','EVT01586; RPT9003'],
 ['Operational impact','Not confirmed','No supplied event records show process disruption, safety impact, outage, or successful PLC state change.','EVT01586 plus absence of impact evidence in supplied event log']
], columns=['assessment','status','basis','key_evidence'])
conclusion.to_csv(OUT/'D2_evidence_conclusions.csv', index=False)

# Parameters / method note
with open(OUT/'D2_method.txt','w') as f:
    f.write('D2 scoring reused the D1 Standardised Logistic Regression pipeline, fixed seed 8213026, excluding date and using the 10 numeric predictors. The D1 operating threshold of 0.31 was applied to the unlabelled investigation set.\n')
    f.write(f'Earliest threshold crossing: {first.date.strftime("%Y-%m-%d")} at probability {first.risk_probability:.6f}; previous day {prev.date.strftime("%Y-%m-%d")} at {prev.risk_probability:.6f}.\n')
    f.write('Timeline contains 16 event IDs and 10 intelligence/report/IOC IDs.\n')

print('Created:', OUT)
print('\nTop 10 risk days:')
print(inv.sort_values('risk_probability', ascending=False).head(10)[['date','risk_probability','risk_flag_0_31']].to_string(index=False))
print('\nEscalation:')
print(first.date.date(), first.risk_probability, 'previous', prev.date.date(), prev.risk_probability)